WepApp/Controllers/ForumPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Domain.Interfaces;
using Domain.Models;
using WepApp.Extensions;

namespace WepApp.Controllers
{
    public class ForumPostController : Controller
    {
        private readonly IDatabase _database;

        private readonly IForumManager _forumManager;

        public ForumPostController(IDatabase database, IForumManager forumManager)
        {
            _database = database;

            _forumManager = forumManager;
        }

        public IActionResult Index(int threadId)
        {
            var thread = _database.ForumThreads.First(x => x.Id == threadId);

            var threadAuthor = _database.Users.First(x => x.Id == thread.UserId);
            
            var directory = _database.ForumDirectories.First(x => x.Id == thread.DirectoryId);

            var userPosts = new List<(ForumPost, User)>();

            foreach(var post in _database.ForumPosts)
            {
                if (post.ThreadId == thread.Id)
                {
                    userPosts.Add(((post, _database.Users.First(x => x.Id == post.UserId))));
                }
            }

            return View((directory, (thread, threadAuthor), userPosts));
        }

        [HttpGet]
        public IActionResult Create(int threadId)
        {
            return View(new ForumPost { ThreadId = threadId });
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_database.ForumPosts.Find(x=>x.Id == id));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_database.ForumPosts.Find(x => x.Id == id));
        }

        [HttpPost]
        public IActionResult Create(ForumPost forumPost)
        {
            if (!this.ExecuteTask(() => _forumManager.CreatePost(forumPost)))
            {
                return View();
            }

            return RedirectToAction("Index", new { threadId = forumPost.ThreadId });
        }

        [HttpPost]
        public IActionResult Edit(ForumPost forumPost)
        {
            if (!this.ExecuteTask(() => _forumManager.EditPost(forumPost)))
                return View(forumPost);

            return RedirectToAction("Index", new { threadId = forumPost.ThreadId });
        }

        [HttpPost]
        public IActionResult Delete(ForumPost forumPost)
        {
            if (!this.ExecuteTask(() => _forumManager.DeletePost(forumPost)))
                return View(forumPost);

            return RedirectToAction("Index", new { threadId = forumPost.ThreadId });
        }
    }
}

WepApp/Controllers/ForumThreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Domain.Interfaces;
using Domain.Models;
using WepApp.Extensions;

namespace WepApp.Controllers
{
    public class ForumThreadController : Controller
    {
        private IForumManager _forumManager;

        private IDatabase _database;

        public ForumThreadController(IForumManager forumManager, IDatabase database)
        {
            _forumManager = forumManager;

            _database = database;
        }

        public IActionResult Index(int directoryId)
        {
            var directory = _database.ForumDirectories.Find(x => x.Id == directoryId);

            var threads = _database.ForumThreads.FindAll(x => x.DirectoryId == directoryId);

            var userThreads = new List<(ForumThread, User)>();

            foreach(var thread in threads)
            {
                userThreads.Add((thread, _database.Users.Find(x => x.Id == thread.UserId)));
            }


            return View((directory, userThreads));
        }

        [HttpGet]
        public IActionResult Create(int directoryId)
        {
            return View(new ForumThread { DirectoryId = directoryId });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_database.ForumThreads.Find(x => x.Id == id));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_database.ForumThreads.Find(x => x.Id == id));
        }

        [HttpPost]
        public IActionResult Create(ForumThread forumThread)
        {
            if (!this.ExecuteTask(() => _forumManager.CreateThread(forumThread)))
                return View(forumThread);

            return RedirectToAction("Index", new { directoryId = forumThread.DirectoryId });
        }


        [HttpPost]
        public IActionResult Edit(ForumThread forumThread)
        {
            if (!this.ExecuteTask(() => _forumManager.EditThread(forumThread)))
                return View(forumThread);

            return RedirectToAction("Index", new { directoryId = forumThread.DirectoryId });
        }

        [HttpPost]
        public IActionResult Delete(ForumThread forumThread)
        {
            if (!this.ExecuteTask(() => _forumManager.DeleteThread(forumThread)))
                return View();

            return RedirectToAction("Index", new { directoryId = forumThread.DirectoryId });
        }
    }
}

WepApp/Views/ForumThread/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model ForumThread
<h1>Opret forum tråd</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Create", "ForumThread", FormMethod.Post))
{
    @Html.HiddenFor(m => m.DirectoryId)

    <b>Titel</b>
    @Html.TextBoxFor(m => m.Title)
    @Html.ValidationMessageFor(m => m.Title)
    <br />
    <input type="submit" value="Opret" />
}

WepApp/Views/ForumThread/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ForumThread
<h1>Slet forum tråd</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Delete", "ForumThread", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Title)

    <b>Titel</b>
    @Html.DisplayTextFor(m => m.Title)
    <br />
    <input type="submit" value="Slet" />
}

WepApp/Views/ForumThread/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ForumThread
<h1>Rediger forum tråd</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Edit", "ForumThread", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Title)

    <b>Titel</b>
    @Html.TextBoxFor(m => m.Title)
    @Html.ValidationMessageFor(m => m.Title)
    <br />
    <input type="submit" value="Rediger" />
}

WepApp/Views/ForumThread/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model (ForumDirectory Directory, List<(ForumThread Thread, User Author)> UserThreads)

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

<h1>@Model.Directory.Name</h1>
<hr />
@foreach (var userThread in Model.UserThreads)
{
    <h2>@Html.ActionLink(userThread.Thread.Title, "Index", "ForumPost", new { threadId = userThread.Thread.Id })</h2>
    <b>af @userThread.Author.Username - @userThread.Thread.Created.ToShortDateString()</b><br />
    @Html.ActionLink("Rediger ", "Edit", "ForumThread", new { id = userThread.Thread.Id })
    @Html.ActionLink("Slet ", "Delete", "ForumThread", new { id = userThread.Thread.Id })
    <hr />
}

@Html.ActionLink("Ny tråd", "Create", "ForumThread", new { directoryId = Model.Directory.Id })