WepApp/Controllers/AssignmentReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Domain.Interfaces;
using Domain.Models;
using WepApp.Extensions;

namespace WepApp.Controllers
{
    public class AssignmentReplyController : Controller
    {
        private IDatabase _database;

        private IAssignmentManager _assignmentManager;

        public AssignmentReplyController(IDatabase database, IAssignmentManager assignmentManager)
        {
            _database = database;

            _assignmentManager = assignmentManager;
        }

        public IActionResult Index(int assignmentId)
        {
            var assignment = _database.Assignments.Find(x => x.Id == assignmentId);

            var assignmentAuthor = _database.Users.Find(x => x.Id == assignment.UserId);

            var assignmentReplyDetails = new List<(AssignmentReply Reply, User Author, int Upvotes, int Downvotes)>();

            foreach(var reply in _database.AssignmentReplies.FindAll(x => x.AssignmentId == assignmentId))
            {
                var replyAuthor = _database.Users.Find(x => x.Id == reply.UserId);

                var upvotes = _database.AssignmentReplyVotes.Where(x => x.AssignmentReplyId == reply.Id)
                    .Count(x => x.Vote == VoteType.Upvote);

                var downvotes = _database.AssignmentReplyVotes.Where(x => x.AssignmentReplyId == reply.Id)
                    .Count(x => x.Vote == VoteType.Downvote);

                assignmentReplyDetails.Add((reply, replyAuthor, upvotes, downvotes));
            }

            return View(((assignment, assignmentAuthor), assignmentReplyDetails));
        }

        [HttpGet]
        public IActionResult Create(int assignmentId)
        {
            return View(new AssignmentReply { AssignmentId = assignmentId });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_database.AssignmentReplies.Find(x => x.Id == id));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_database.AssignmentReplies.Find(x => x.Id == id));
        }

        [HttpPost]
        public IActionResult Create(AssignmentReply assignmentReply)
        {
            if(!this.ExecuteTask(() => _assignmentManager.CreateAssignmentReply(assignmentReply)))
                return View(assignmentReply);

            return RedirectToAction("Index", new { assignmentId = assignmentReply.AssignmentId });
        }

        [HttpPost]
        public IActionResult Edit(AssignmentReply assignmentReply)
        {
            if (!this.ExecuteTask(() => _assignmentManager.EditAssignmentReply(assignmentReply)))
                return View(assignmentReply);

            return RedirectToAction("Index", new { assignmentId = assignmentReply.AssignmentId });
        }

        [HttpPost]
        public IActionResult Delete(AssignmentReply assignmentReply)
        {
            if (!this.ExecuteTask(() => _assignmentManager.DeleteAssignmentReply(assignmentReply)))
                return View(assignmentReply);

            return RedirectToAction("Index", new { assignmentId = assignmentReply.AssignmentId });
        }
    }
}

WepApp/Controllers/AssignmentReplyVoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Domain.Models;
using WepApp.Extensions;
using Domain.Interfaces;

namespace WepApp.Controllers
{
    public class AssignmentReplyVoteController : Controller
    {
        private readonly IAssignmentManager _assignmentManager;

        private readonly IDatabase _database;

        public AssignmentReplyVoteController(IAssignmentManager assignmentManager,
            IDatabase database)
        {
            _assignmentManager = assignmentManager;

            _database = database;
        }

        [HttpGet]
        public IActionResult Create(int assignmentReplyId, VoteType vote)
        {
            return View(new AssignmentReplyVote { AssignmentReplyId = assignmentReplyId, Vote = vote });
        }

        [HttpPost]
        public IActionResult Create(AssignmentReplyVote assignmentReplyVote)
        {
            if (!this.ExecuteTask(() => _assignmentManager.CreateAssignmentReplyVote(assignmentReplyVote)))
                return View(assignmentReplyVote);

            var assignmentReply = _database.AssignmentReplies.Find(x => x.Id == assignmentReplyVote.AssignmentReplyId);

            return RedirectToAction("Index", "AssignmentReply", new { assignmentId = assignmentReply.AssignmentId });
        }
    }
}

WepApp/Views/AssignmentReply/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model AssignmentReply
<h1>Opret besvarelse</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Create", "AssignmentReply", FormMethod.Post))
{
    @Html.HiddenFor(m => m.AssignmentId)

    <b>Besvarelse:</b><br />
    @Html.TextBoxFor(m => m.Text)

    <br />
    <input type="submit" value="Opret" />
}

WepApp/Views/AssignmentReply/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model AssignmentReply
<h1>Slet besvarelse</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Delete", "AssignmentReply", FormMethod.Post))
{
    @Html.HiddenFor(m => m.AssignmentId)
    @Html.HiddenFor(m => m.Text)

    <b>Besvarelse:</b><br />
    @Html.DisplayTextFor(m => m.Text)
    <br />
    <input type="submit" value="Slet" />
}

WepApp/Views/AssignmentReply/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model AssignmentReply
<h1>Rediger besvarelse</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Edit", "AssignmentReply", FormMethod.Post))
{
    @Html.HiddenFor(m => m.UserId)
    @Html.HiddenFor(m => m.AssignmentId)

    <b>Besvarelse:</b>
    <br />
    @Html.TextBoxFor(m => m.Text)

    <br />
    <input type="submit" value="Rediger" />
}

WepApp/Views/AssignmentReply/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ((Assignment assignment, User author) AssignmentDetails, List<(AssignmentReply Reply, User Author, int Upvotes, int Downvotes)> AssignmentReplyDetails)

@Html.ValidationSummary(false, "", new { @class = "text-danger" })


<h2>@Model.AssignmentDetails.assignment.Title</h2>
<h4>@Model.AssignmentDetails.assignment.Description</h4>
<b>@Model.AssignmentDetails.author.Username</b>

<hr />

@foreach (var assignmentReplyDetail in Model.AssignmentReplyDetails)
{
    <b>@assignmentReplyDetail.Author.Username</b>
    <br />
    <p>@assignmentReplyDetail.Reply.Text</p>
    <p>Upvotes: @assignmentReplyDetail.Upvotes | Downvotes: @assignmentReplyDetail.Downvotes </p>

    @Html.ActionLink("Vurder ", "Create", "AssignmentReplyVote", new { assignmentReplyId = assignmentReplyDetail.Reply.Id })
    @Html.ActionLink("Rediger ", "Edit", "AssignmentReply", new { id = assignmentReplyDetail.Reply.Id })
    @Html.ActionLink("Slet ", "Delete", "AssignmentReply", new { id = assignmentReplyDetail.Reply.Id })
    <hr />
}

@Html.ActionLink("Ny besvarelse", "Create", "AssignmentReply", new { assignmentId = Model.AssignmentDetails.assignment.Id })