WepApp/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Database.Context;
using Domain.Models;
using Domain.Interfaces;
using WepApp.Extensions;

namespace WepApp.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly IDatabase _database;

        private readonly IAssignmentManager _assignmentManager;

        public AssignmentController(IDatabase database, IAssignmentManager assignmentManager)
        {
            _database = database;
         
            _assignmentManager = assignmentManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userAssignments = new List<(Assignment, User)>();

            foreach(var assignment in _database.Assignments)
            {
                userAssignments.Add((assignment, _database.Users.First(x=>x.Id == assignment.UserId)));
            }

            return View(userAssignments);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Assignment assignment)
        {
            if(!this.ExecuteTask(()=> _assignmentManager.CreateAssignment(assignment)))
                return View();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_database.Assignments.ToList().Find(x=>x.Id == id));
        }

        [HttpPost]
        public IActionResult Edit(Assignment assignment)
        {
            if(!this.ExecuteTask(() => _assignmentManager.EditAssignment(assignment)))
            {
                return View();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_database.Assignments.Find(x=>x.Id == id));
        }

        [HttpPost]
        public IActionResult Delete(Assignment assignment)
        {
            if (!this.ExecuteTask(() => _assignmentManager.DeleteAssignment(assignment)))
                return View(assignment);

            return RedirectToAction("Index");
        }
    }
}

WepApp/Controllers/AssignmentReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Domain.Interfaces;
using Domain.Models;
using WepApp.Extensions;

namespace WepApp.Controllers
{
    public class AssignmentReplyController : Controller
    {
        private IDatabase _database;

        private IAssignmentManager _assignmentManager;

        public AssignmentReplyController(IDatabase database, IAssignmentManager assignmentManager)
        {
            _database = database;

            _assignmentManager = assignmentManager;
        }

        public IActionResult Index(int assignmentId)
        {
            var assignment = _database.Assignments.Find(x => x.Id == assignmentId);

            var assignmentAuthor = _database.Users.Find(x => x.Id == assignment.UserId);

            var assignmentReplyDetails = new List<(AssignmentReply Reply, User Author, int Upvotes, int Downvotes)>();

            foreach(var reply in _database.AssignmentReplies.FindAll(x => x.AssignmentId == assignmentId))
            {
                var replyAuthor = _database.Users.Find(x => x.Id == reply.UserId);

                var upvotes = _database.AssignmentReplyVotes.Where(x => x.AssignmentReplyId == reply.Id)
                    .Count(x => x.Vote == VoteType.Upvote);

                var downvotes = _database.AssignmentReplyVotes.Where(x => x.AssignmentReplyId == reply.Id)
                    .Count(x => x.Vote == VoteType.Downvote);

                assignmentReplyDetails.Add((reply, replyAuthor, upvotes, downvotes));
            }

            return View(((assignment, assignmentAuthor), assignmentReplyDetails));
        }

        [HttpGet]
        public IActionResult Create(int assignmentId)
        {
            return View(new AssignmentReply { AssignmentId = assignmentId });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_database.AssignmentReplies.Find(x => x.Id == id));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_database.AssignmentReplies.Find(x => x.Id == id));
        }

        [HttpPost]
        public IActionResult Create(AssignmentReply assignmentReply)
        {
            if(!this.ExecuteTask(() => _assignmentManager.CreateAssignmentReply(assignmentReply)))
                return View(assignmentReply);

            return RedirectToAction("Index", new { assignmentId = assignmentReply.AssignmentId });
        }

        [HttpPost]
        public IActionResult Edit(AssignmentReply assignmentReply)
        {
            if (!this.ExecuteTask(() => _assignmentManager.EditAssignmentReply(assignmentReply)))
                return View(assignmentReply);

            return RedirectToAction("Index", new { assignmentId = assignmentReply.AssignmentId });
        }

        [HttpPost]
        public IActionResult Delete(AssignmentReply assignmentReply)
        {
            if (!this.ExecuteTask(() => _assignmentManager.DeleteAssignmentReply(assignmentReply)))
                return View(assignmentReply);

            return RedirectToAction("Index", new { assignmentId = assignmentReply.AssignmentId });
        }
    }
}

WepApp/Views/Assignment/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Assignment

<h1>Opret opgave</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Create", "Assignment", FormMethod.Post))
{
    <p>Titel</p>
    @Html.TextBoxFor(m => m.Title)
    <p>Beskrivelse</p>
    @Html.TextAreaFor(m => m.Description)

    <input type="submit" value="Opret opgave" />
}

WepApp/Views/Assignment/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model Assignment

<h1>Slet opgave</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Delete", "Assignment", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Title)
    @Html.HiddenFor(m => m.Description)

    <b>Titel</b>
    @Html.DisplayTextFor(m => m.Title)<br />
    <b>Beskrivelse</b><br />
    @Html.DisplayTextFor(m => m.Description)
    <br />
    <input type="submit" value="Slet" />
}

WepApp/Views/Assignment/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Assignment

<h1>Rediger opgave</h1>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Edit", "Assignment", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)

    <b>Titel</b>
    @Html.TextBoxFor(m => m.Title)<br />
    <b>Beskrivelse</b><br />
    @Html.TextAreaFor(m => m.Description)<br />

    <input type="submit" value="Ret opgave" />
}

WepApp/Views/Assignment/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model List<(Assignment Assignment, User Author)>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@foreach (var userAssignment in Model)
{
    <h2>
        @Html.ActionLink(@userAssignment.Assignment.Title, "Index", "AssignmentReply", new { assignmentId = userAssignment.Assignment.Id })
    </h2>
    <b>af @userAssignment.Author.Username</b>
    <p>@userAssignment.Assignment.Description</p>
    @Html.ActionLink("Ret ", "Edit", "Assignment", new { id = userAssignment.Assignment.Id })
    @Html.ActionLink("Slet", "Delete", "Assignment", new { id = userAssignment.Assignment.Id })
    <hr />
}

@Html.ActionLink("Ny opgave", "Create", "Assignment")